### ISSUE TITLE
error when running

### ISSUE THREAD

**Issue by rastiazul** [pxsocs/cryptoblotter#11]
Im getting the following error:
(cb_env) rastiazul@cuita:~/cryptoblotter$ python run.py
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    from cryptoalpha import create_app
  File "/home/rastiazul/cryptoblotter/cryptoalpha/__init__.py", line 6
SyntaxError: Non-ASCII character '\xe2' in file /home/rastiazul/cryptoblotter/cryptoalpha/__init__.py on line 6, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by pxsocs** [comment]
Can you confirm which version of python you are using?
`python --version`

**Comment by rastiazul** [comment]
Python 2.7.12

**Comment by pxsocs** [comment]
Python 3.6 or higher is needed. Follow the instructions at the [Installation Guide](https://github.com/pxsocs/cryptoblotter/blob/master/INSTALL.MD) under Step 4 to get Python 3.6.

**Comment by rastiazul** [comment]
thank you, I installed 3.6 but its still saying I have 2.7 and still getting the error...

**Comment by rastiazul** [comment]
I read that the python command will always be python 2.x and for python 3.x the command is python3

**Comment by pxsocs** [comment]
You can set the python alias to point to python3. More info [here](https://stackoverflow.com/questions/34680228/switch-between-python-2-7-and-python-3-5-on-mac-os-x). 

But I've updated the install instructions to explicitly call `python3 run.py`

**Comment by rastiazul** [comment]
Now im getting a different error:
```
(cb_env) rastiazul@cuita:~/cryptoblotter$ python3 run.py
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    from cryptoalpha import create_app
  File "/home/rastiazul/cryptoblotter/cryptoalpha/__init__.py", line 12, in <module>
    from flask import Flask
ImportError: No module named 'flask'
```
I tried installing python-flask but it didnt make a difference. There are a bunch of other python-flask things to install like python-flash api so I dont know if its one of those

I use linux btw

**Comment by pxsocs** [comment]
This is probably because you installed python3 and all the pip packages are under python2.
Try the following:

__Navigate to your default cryptoblotter directory__
`$ cd /home/rastiazul/cryptoblotter/`

__Activate your virtual environment if not done__
`$ source cb_env/bin/activate`

__Install all required pip packages forcing pip3__
`(cb_env)$ pip3 install -r requirements.txt`

__run using python3:__
`(cb_env)$ python3 run.py`

**Comment by rastiazul** [comment]
ok thank you, it ran but I cant connect to http://127.0.0.1:5000/. it says connection refused 
```
----------------------------------------
         Welcome to the Matrix
----------------------------------------
Application loaded...
You can access it at your browser
Just go to:
http://127.0.0.1:5000/
----------------------------------------
And don't forget to take your red pills
----------------------------------------
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    app = create_app()
  File "/home/rastiazul/cryptoblotter/cryptoalpha/__init__.py", line 54, in create_app
    from cryptoalpha.users.routes import users
  File "/home/rastiazul/cryptoblotter/cryptoalpha/users/routes.py", line 26
    flash(f'Account created for {form.username.data}. You can now Login.',
                                                                        ^
SyntaxError: invalid syntax

```

**Comment by pxsocs** [comment]
Should work. Just to be sure, at the cryptoblotter directory execute:
`git pull origin master`
`python3 run.py`

**Comment by rastiazul** [comment]
I see the fancy text but still cant connect :(

```

-----------------------------------------------------------------
  ____                  _        ____  _       _   _
 / ___|_ __ _   _ _ __ | |_ ___ | __ )| | ___ | |_| |_ ___ _ __
| |   | '__| | | | '_ \| __/ _ \|  _ \| |/ _ \| __| __/ _ \ '__|
| |___| |  | |_| | |_) | || (_) | |_) | | (_) | |_| ||  __/ |
 \____|_|   \__, | .__/ \__\___/|____/|_|\___/ \__|\__\___|_|
            |___/|_|

-----------------------------------------------------------------
               Privacy Focused Portfolio Tracker
-----------------------------------------------------------------

Application loaded...
You can access it at your browser
Just go to:
http://127.0.0.1:5000/
TO EXIT HIT CTRL+C a couple of times
You can minimize this window now...

-----------------------------------------------------------------
                  Always go for the red pill
-----------------------------------------------------------------


Traceback (most recent call last):
  File "run.py", line 6, in <module>
    app = create_app()
  File "/home/rastiazul/cryptoblotter/cryptoalpha/__init__.py", line 78, in create_app
    from cryptoalpha.users.routes import users
  File "/home/rastiazul/cryptoblotter/cryptoalpha/users/routes.py", line 26
    flash(f'Account created for {form.username.data}. You can now Login.',
                                                                        ^
SyntaxError: invalid syntax

```

**Comment by pxsocs** [comment]
This is unexpected. The error is coming from the following line of code:
```
flash(f'Account created for {form.username.data}. You can now Login.',
              'success')
```
And it seems to be returning `invalid syntax` because of the line break. That shouldn't happen for Python 3.7 (which is the version I'm running).  

Can you execute the following and paste the results here:
```
$ python3 --version
$ cat debug.log 
```
For debug.log just paste the last 5 lines.

**Comment by rastiazul** [comment]
Python 3.5.2
2019-06-12 12:17:52,788:INFO:Starting main program...
2019-06-12 12:17:52,788:INFO:[create_app] Started create_app function
2019-06-13 07:30:27,802 INFO <module>(28) Initializing Database
2019-06-13 07:30:27,803 INFO <module>(37) Starting main program...
2019-06-13 07:30:27,804 INFO create_app(70) [create_app] Started create_app function

**Comment by pxsocs** [comment]
Can you try the following and paste the results here (make sure to copy the Python code as is below, including the line break on `b=..`:

`python3`

<Python will open>

```
a = 'test'
b = (f'Account created for {a}. You can now Login.',
              'success')
print(b)
exit()
```

<Python will exit - copy results above>

**Comment by rastiazul** [comment]
(cb_env) rastiazul@cuita:~/cryptoblotter$ python3
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> a = 'test'
>>> b = (f'Account created for {a}. You can now Login.',
  File "<stdin>", line 1
    b = (f'Account created for {a}. You can now Login.',
                                                      ^
SyntaxError: invalid syntax
>>>               'success')
  File "<stdin>", line 1
    'success')
    ^
IndentationError: unexpected indent
>>> print(b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'b' is not defined
>>> exit()

**Comment by rastiazul** [comment]
or what is like this:
python3

a = 'test'
b = (f'Account created for {a}. You can now Login.',
              'success')
print(b)
exit()

**Comment by pxsocs** [comment]
You need to upgrade to Python 3.6 or higher. f-strings are only supported on 3.6+. 

Upgrade instructions [here](https://jcutrer.com/linux/upgrade-python37-ubuntu1810)

This should fix the issues.
