### ISSUE TITLE
missing  cryptoblotter/cryptoalpha/static/downloads/sample.csv 

### ISSUE THREAD

**Issue by ac-com-au** [pxsocs/cryptoblotter#12]
missing sample.csv file

**Comment by pxsocs** [comment]
I assume the broken link is at http://127.0.0.1:5000/csvtemplate . 

Tested in the offline version and it works but on the http://www.cryptoblotter.io/csvtemplate page it doesn't work. So seems like a problem with the relative path. Looking into it. In the mean time, attaching the file here:  
[sample.csv.zip](https://github.com/pxsocs/cryptoblotter/files/3293447/sample.csv.zip)

**Comment by pxsocs** [comment]
This is now fixed and will be updated with the next GIT push to this repository.
