### ISSUE TITLE
Install notes for windows

### ISSUE THREAD

**Issue by mrfearless** [pxsocs/cryptoblotter#8]
For windows users, might require a note or a section in the Install.md to reference a few particular steps that are specific to installation of cryptoblotter on windows os.

- As there is no `source` command in windows this command: `source cb_env/bin/activate` will cause an error. On windows there doesn't appear to be a `bin` folder under the `cb_env` folder. The script (batch file) for activating can be called at the command prompt from within the crypoblotter directory like so: `.\cb_env\scripts\activate`

- The `export` command will similarly cause an error from the command prompt:
```
export ALPHAVANTAGE_API_KEY=YUI9BS0MIBOPWRVR
export SECRET_KEY=44600d69123eb71e1338e47587fec5fb
export SQLALCHEMY_DATABASE_URI=sqlite:///alpha.db
```
and can be changed to use the `set` windows command instead to set the environment variables:
```
SET ALPHAVANTAGE_API_KEY=YUI9BS0MIBOPWRVR
SET SECRET_KEY=44600d69123eb71e1338e47587fec5fb
SET SQLALCHEMY_DATABASE_URI=sqlite:///alpha.db
```

**Comment by pxsocs** [comment]
Thanks! Windows instructions coming in next release. This is very helpful so I can get started.

**Comment by pxsocs** [comment]
Windows Installation instructions are now under [INSTALL.MD](https://github.com/pxsocs/cryptoblotter/blob/master/INSTALL.MD#quick-installation-windows)

Since I'm not a heavy Windows user, would appreciate any feedback users may have in this process.
