### ISSUE TITLE
Missing Navigation Bar in some systems

### ISSUE THREAD

**Issue by pxsocs** [pxsocs/cryptoblotter#9]
An issue is preventing the Top Navigation bar from showing. 
I cannot replicate this on my side at this moment.

**Comment by pxsocs** [comment]
This was originally referenced under Issue #7 - details below. 

- __Along the top of the page there is no menu bar like in the preview image, with Account Tools, Portfolio Actions, Portfolio Analysis, Other Tools, settings, logout buttons. I tried logging in via firefox 67.0.1 and chrome, but that menu bar is not visible on either.__
    -  That's odd and I haven't witnessed this behavior. On Chrome, can you:
        - Right click at the page and select __Inspect__
        - Verify on the `Console` under `errors`, if there are any errors related to Bootstrap or any mention of `layout.html`.
        - Under `Elements`, verify if the HTML for the header is present. Particularly the Navigation bar. Should start with: 
        ```
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        ```
        - Finally, can you navigate to [http://127.0.0.1:5000/about](http://127.0.0.1:5000/about) and confirm if the issue is present there as well.
        __I'm opening a new Issue for this specific topic - [please respond here](https://github.com/pxsocs/cryptoblotter/issues/9).__

**Comment by mrfearless** [comment]
Console only seems to show an endless list of blockexplorer.com errors:
![](https://i.postimg.cc/qvRXW2F1/console-error.png)

The elements does show the navbar, its just not visible - however it appeas that the mouse change to hand pointer when moving over where the buttons should be and clicking does bring up a menu that is visible. Just the bar is invisible:
![](https://i.postimg.cc/Hs39S66J/navbar.png)

**Comment by pxsocs** [comment]
Not being able to replicate this. 
But I'm suspecting it may have something to do with the issue with blockexplorer. 
I've pushed an updated version to [Cryptoblotter.io](http://www.cryptoblotter.io). Before I update in Github, can you login with demo@demo.com (pass: demo) at the link above and check if the issue persists?

**Comment by mrfearless** [comment]
The demo at cryptoblotter.io seems to work fine, the nav bar is visable and is working fine.

**Comment by pxsocs** [comment]
Great. The fix seems to have worked. Pushed a new version to GitHub with the fix. 

`$ git pull origin master` in your installed directory.
 
Closing this issue but let me know if doesn't work.
